### ISSUE TITLE
Unable to call vault behind forwarding Proxy

### ISSUE THREAD

**Issue by jan-schumacher** [sethvargo/vault-kubernetes-authenticator#13]
Somehow the communication is with vault behind a proxy is not possible.
After debugging and fiddeling around it seems that the https_proxy env variable is just ignored.
When I set the proxy in the transport struct manually like this:
```
transport := &http.Transport{
	TLSClientConfig: tlsClientConfig,
}
transport.Proxy = http.ProxyFromEnvironment
```

It works just fine.

**Comment by sethvargo** [comment]
I think we want to use https://golang.org/pkg/net/http/#ProxyFromEnvironment instead, but yea, this wasn't something I considered when writing this.

**Comment by jan-schumacher** [comment]
@sethvargo I created a pullrequest for you. https://github.com/sethvargo/vault-kubernetes-authenticator/pull/14

**Comment by jan-schumacher** [comment]
@sethvargo nice, you already merged it. Do you create a new container version?

**Comment by sethvargo** [comment]
0.3.0 is out
