### ISSUE TITLE
Add Vault namespace variable

### ISSUE THREAD

**Issue by samoidor** [sethvargo/vault-kubernetes-authenticator#15]
Is it possible to specify a vault namespace, adding an VAULT_NAMESPACE variable and handling it in the curl with X-Vault-Namespace header or with the path ?

**Comment by sethvargo** [comment]
Hi @samoidor 

Happy to do so - can you link to some docs or API about this feature?

**Comment by samoidor** [comment]
Hi @sethvargo
Thanks a lot for your quick response.
Here is a link for the feature. 
https://www.vaultproject.io/docs/enterprise/namespaces/index.html#usage
Please don't hesitate to contact me if you need.

**Comment by samoidor** [comment]
Hi @sethvargo 
Thanks a lot for your help.
Do you plan to build a new image on [docker hub](https://hub.docker.com/r/sethvargo/vault-kubernetes-authenticator) with the feature soon ?

**Comment by sethvargo** [comment]
@samoidor you'll be pleased to know that I cut a new release and built the docker images locally... then never pushed them 🤦‍♂. 0.4.0 is up now. Sorry about that!

**Comment by samoidor** [comment]
Thanks
