### ISSUE TITLE
support for GCP auth

### ISSUE THREAD

**Issue by joemiller** [sethvargo/vault-kubernetes-authenticator#2]
This is not an issue so much as a pointer that might help others. I have created a fork of this repo that performs the [Vault GCP auth](https://www.vaultproject.io/docs/auth/gcp.html) using a Google Cloud instance's [instance identity token](https://cloud.google.com/compute/docs/instances/verifying-instance-identity)

https://github.com/pantheon-systems/vault-gcp-authenticator

The code and process is almost identical to the K8S authentication with the exception of reading the JWT token from the metadata API instead of from a file as in the K8S auth.

I also made some changes that were desirable for our environment such as using the Vault Go client lib so that all of the standard `VAULT_*` environment variables are available.

It might be nice to combine the k8s and gcp auth mechanisms into a common binary at some point. Or maybe both will end up in the new Vault agent code.

**Comment by sethvargo** [comment]
Hey @joemiller 

Thanks for reaching out. I think this is HashiCorp's idea behind https://www.vaultproject.io/docs/agent/index.html (a single agent that does it all). For now, I'm trying to keep this super duper simple in case people want to build something on top of it (legos and all).
