### ISSUE TITLE
Renewing and revoking tokens

### ISSUE THREAD

**Issue by ahume** [sethvargo/vault-kubernetes-authenticator#6]
Recognising this wouldn't be possible in an initContainer, but do you think there is scope for adding the ability to deal with future management of the retrieved token?

For example, renewing tokens periodically and revoking them when the pod shuts down. Or do you think this is better in a separate application in a sidecar, or in the application container itself? Wondering what your approach to this has been.

**Comment by sethvargo** [comment]
Hi @ahume 

Usually you push this off to something like Consul Template (which handles renewal, revocation, etc). You might also want to look at vault-agent: https://www.vaultproject.io/docs/agent/index.html

**Comment by ahume** [comment]
Thanks for your advice Seth. I've implemented Consul Template to handle renewals (works fine even without a template), and a small sh script on pod kill to revoke. This seems to be working out well.
