### ISSUE TITLE
update example due to bug in 0.1.0 release

### ISSUE THREAD

**Issue by natehudson** [sethvargo/vault-kubernetes-authenticator#7]
Hi, thanks for the code.

Is there anyway you can update the example manifest to use:

`image: sethvargo/vault-kubernetes-authenticator:0.1.2` or `latest`
instead of:
`image: sethvargo/vault-kubernetes-authenticator:0.1.0`

I spent a few hours debugging a `{"errors":["missing client token"]}` error with the 0.1.0 version and a new vault setup before going to the docker hub and noticing the new tag which fixed my problem.

I know this is trivial, but I figured it might save someone else some time. Thanks.

**Comment by sethvargo** [comment]
Fixed
