### ISSUE TITLE
Support for running init container as non root user

### ISSUE THREAD

**Issue by narendrakadali** [sethvargo/vault-kubernetes-authenticator#8]
currently , this project does not supporting running init container as non root user. This will create challenges when we want to run other container as non root user.  It will create permission related issues where vault token is mounted and ultimately the other container won't be able to read the vault token.

**Comment by snahelou** [comment]
You can add ca-cert by yourself: 
```diff
-FROM scratch
+FROM alpine:latest
 ADD https://curl.haxx.se/ca/cacert.pem /etc/ssl/certs/ca-certificates.crt
+RUN apk --no-cache add ca-certificates && update-ca-certificates
```

BR
